[package]
name = "kde-ocl-sys"
version = "0.1.0"
authors = ["davenza"]

[lib]
crate-type = ["cdylib"]


[dependencies]
libc = "*"
ndarray = { version = "0.12" }
num = "*"
fnv = "1.0.3"
ocl = "0.19"

[build-dependencies]
cbindgen = "0.9.1"